name: "Env and Scope Var Setter"

runs:
  using: "composite"
  steps:
      - name: Set secrets as env var
        shell: bash
        run: |
          set -x
          ${{secrets.GCP_SA_GHA_PLAYPCI_DEPLOYMENT}}
          ${{secrets.GCP_SA_GHA_PLAYPCI_TERRAFORM}}
