name: "Validate Deployment"
description: "Authenticate and Validate Deployent"

inputs:
#  google_credentials:
#    description: "Google Credentials"
#    required: true
#  google_project_id:
#    description: "Google Project Id"
#    required: true
#  k8s_cluster_name:
#    description: "K8s cluster name"
#    required: true
#  k8s_cluster_region:
#    description: "K8s cluster region"
#    required: true
  app_name:
    description: "name of the service"
    required: true
  git_sha:
    description: "expected git sha"
    required: true
  max_attempt:
    description: "max health check retry"
    required: false
  sleep_time:
    description: "sleep between retries"
    required: false

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v2
      - name: perform deployment validation
        shell: bash
        run: |
          ./script.py -a ${{inputs.app_name}} -g ${{inputs.git_sha}} -s ${{inputs.sleet_time}} -m ${{inputs.sleep_time}}
