name: Trigger Deploy and wait
description: This action trigger deployment on dev
inputs:
  token:
    required: true
    description: Github Auth Token
  repoName:
    required: true
    description: GitHub Repo Name
  gitSha:
    required: true
    description: GitHub Sha

runs:
  using: docker
  image: 'Dockerfile'

branding:
  icon: arrow-down
  color: blue