name: test triggerDeployer

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: 'Repo name'
        required: true
        default: 'my repo name'
      gitSha:
        description: 'Git Sha to deploy'
        required: true
        default: '1234567'
      deployerName:
        description: "name of the yaml workflow file"
        required: true
        default: 'dev-pci'

env:
  GIT_SHA: ${{ github.event.inputs.target-env }}


jobs:
  execute-smoke-test:
    name: trigger devDeployer
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Application
        uses: gocariq/devops/customActions/triggerDeployer@main
        with:
         token: ${{secrets.DISPATCH_ACCESS_TOKEN}}
         gitSha: ${{ github.event.inputs.gitSha }}
         repoName: ${{ github.event.inputs.repoName }}
         deployerName: ${{ github.event.inputs.deployerName }}